### ISSUE TITLE
Incongruent Results

### ISSUE THREAD

**Issue by rajadain** [TheAcademyofNaturalSciences/gwlf-e#8]
Hello,

I made a repo comparing this against the current release: https://github.com/rajadain/mmw-gwlfe-comparison

While the timing improvements look very impressive, I'm finding that all but one input have different results. It seems as if the "first" input has similar results, but further ones diverge, and it doesn't matter what exactly the "first" one is. Could this be because of some sort of memoization? Should I be reinitializing GWLF-E differently than before?

Code for generating output from saved results is here: https://github.com/rajadain/mmw-gwlfe-comparison/blob/master/drexeleds/main.py

Please let me know if you need any clarifications, or have suggestions to test differently. Otherwise feel free to add the inputs listed in https://github.com/rajadain/mmw-gwlfe-comparison/tree/master/tests for testing purposes if useful.

Thanks.

**Comment by gnitsua** [comment]
You're absolutely right that this is what is happening. Because I thought you were running the model from the command line, I didn't think we needed to support multiple runs (and therefor didn't need to pay the performance penalty of providing this feature). Since that clearly won't work, let me add that feature and see how it effects your testing results.

**Comment by rajadain** [comment]
Hmm thanks for confirming that. I think the way Celery works is within the request / response cycle of Django, and perhaps follows the single threaded model. As such, I should be able to adjust my tests, and we might not have to add multirun support. I can confirm that after speaking with my team on Monday. If it is a non-trivial adjustment to add multirun support, please hold off until I have confirmation. Thanks.

**Comment by gnitsua** [comment]
So I have made the changes to enable multi run memoization and I'm trying to test it without merging with master. I changed this in the pip file in drexeleds:
```
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
numba = "==0.38.0"
gwlf-e = {ref = "multirun-memoization", git = "git://github.com/drexeleds/gwlf-e"}

[dev-packages]

[requires]
python_version = "2.7"
```

When I run it however, it doesn't seem to change the output. When I run the model on my local machine after running a few files it works, and I was able to make temporary test that uses the same code and that passes as well. At this point I'm hoping that pip is just not pulling the right code? Am I doing something wrong, or the code still not working.

**Comment by rajadain** [comment]
I'll take a quick look. It's possible that after you change the `Pipfile` you have to run `pipenv install` again to update the dependencies.

**Comment by rajadain** [comment]
Alright, so this works:

```
$ pipenv uninstall gwlf-e
$ pipenv install git+git://github.com/drexeleds/gwlf-e@multirun-memoization#egg=gwlf-e
```

Which seems to install the right version, but then I run into #5, presumably because `multirun-memoization` hasn't been rebased atop `develop` recently.

```
$ make run-drexeleds
bash -c "cd drexeleds; pipenv run python main.py"
Traceback (most recent call last):
  File "main.py", line 43, in <module>
    writer.write(pre_z)
  File "/Users/rajadain/.local/share/virtualenvs/drexeleds-sUBfOwqo/lib/python2.7/site-packages/gwlfe/Parser.py", line 1292, in write
    UnSatStorCarryover_f(z.NYrs, z.DaysMonth, z.Temp, z.InitSnow_0, z.Prec, z.NRur, z.NUrb, z.Area, z.CNI_0,
AttributeError: 'DataModel' object has no attribute 'NYrs'
make: *** [run-drexeleds] Error 1
```

**Comment by gnitsua** [comment]
Oops, I had rebased locally but hadn't pushed. Should be rebased now

**Comment by rajadain** [comment]
Okay, I think this is working! Great job!!

New timing results:

```
huc08
* Average read_input_file speedup: -1.00%
* Average prepare_input_gms speedup: 0.00%
* Average read_input_gms speedup: 2.47%
* Average run_gwlfe speedup: 79.44%
* Average write_output_file speedup: -1202.15%
* Average total speedup: 74.06%

huc10
* Average read_input_file speedup: -7.25%
* Average prepare_input_gms speedup: 0.00%
* Average read_input_gms speedup: 1.20%
* Average run_gwlfe speedup: 77.65%
* Average write_output_file speedup: -44.53%
* Average total speedup: 72.57%

huc12
* Average read_input_file speedup: 1.26%
* Average prepare_input_gms speedup: 0.00%
* Average read_input_gms speedup: 2.41%
* Average run_gwlfe speedup: 78.06%
* Average write_output_file speedup: -2.01%
* Average total speedup: 73.05%

Total
* Average read_input_file speedup: -3.44%
* Average prepare_input_gms speedup: 0.00%
* Average read_input_gms speedup: 1.85%
* Average run_gwlfe speedup: 78.26%
* Average write_output_file speedup: -365.16%
* Average total speedup: 73.11%
```

(Not sure what is going on with `write_output_file`, but that doesn't even touch your code so please disregard).

This is still quite a speedup.

Furthermore, results are now stable and to a very high degree of tolerance: 0.00000000000001

I think this is good to merge on to `develop`. I'll update my test repo.
